In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Une fois votre Drive monté, nous listerons le contenu du dossier pour identifier les fichiers de données. Veuillez vous assurer que le chemin ci-dessous est correct.

In [2]:
import os

data_folder_path = '/content/drive/MyDrive/Datasets_Cleans_Isheero'

if os.path.exists(data_folder_path):
    print(f"Contenu de '{data_folder_path}':")
    for item in os.listdir(data_folder_path):
        print(item)
else:
    print("Erreur ")

Contenu de '/content/drive/MyDrive/Datasets_Cleans_Isheero':
gkg_clean.csv
Events_clean cc de powerBI.xlsx
events_clean.csv
Untitled61.ipynb
Data_Engineering_Hackathon_Isheero.ipynb
daily_score.csv
ML_Engineering_Hackathon__.ipynb
Equipe10_Plateforme d'analyse géopolitique du Bénin_.pbix
Lien_dashboard .gdoc

In [3]:
import pandas as pd

# Charger gkg_clean.csv
try:
    gkg_df = pd.read_csv(f'{data_folder_path}/gkg_clean.csv')
    print("gkg_clean.csv chargé avec succès.")
    print("Premières 5 lignes de gkg_df:")
    display(gkg_df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier gkg_clean.csv n'a pas été trouvé dans '{data_folder_path}'.")

# Charger events_clean.csv
try:
    events_df = pd.read_csv(f'{data_folder_path}/events_clean.csv')
    print("\nevents_clean.csv chargé avec succès.")
    print("Premières 5 lignes de events_df:")
    display(events_df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier events_clean.csv n'a pas été trouvé dans '{data_folder_path}'.")

# Charger daily_score.csv
try:
    daily_score_df = pd.read_csv(f'{data_folder_path}/daily_score.csv')
    print("\ndaily_score.csv chargé avec succès.")
    print("Premières 5 lignes de daily_score_df:")
    display(daily_score_df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier daily_score.csv n'a pas été trouvé dans '{data_folder_path}'.")

# Charger Events_clean cc de powerBI.xlsx
try:
    events_excel_df = pd.read_excel(f'{data_folder_path}/Events_clean cc de powerBI.xlsx')
    print("\nEvents_clean cc de powerBI.xlsx chargé avec succès.")
    print("Premières 5 lignes de events_excel_df:")
    display(events_excel_df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier Events_clean cc de powerBI.xlsx n'a pas été trouvé dans '{data_folder_path}'.")
except Exception as e:
    print(f"Erreur lors du chargement de Events_clean cc de powerBI.xlsx: {e}")

gkg_clean.csv chargé avec succès.
Premières 5 lignes de gkg_df:

,DATE,DocumentIdentifier,V2Locations,V2Persons,V2Organizations,V2Counts,SharingImage,tone,positive_score,negative_score,polarity,themes,themes_count,has_crisis_theme
0,1970-01-01 05:37:31.202161500,https://fr.allafrica.com/stories/202512020485....,1#Niger#NG#NG##16#8#NG#44;1#Niger#NG#NG##16#8#...,NaN,"Authority Of Basin Of Niger Them,49;Authority ...",NaN,no_image,5.944056,5.944056,0.000000,5.944056,"['SLFID_NATURAL_RESOURCES,1013', 'WB_471_ECONO...",39,True
1,1970-01-01 05:37:31.202161500,https://fr.allafrica.com/stories/202512020413....,1#Seychelles#SE#SE##-4.583333#55.666667#SE#167...,NaN,"Federation Madagascar,1180",NaN,no_image,1.259446,3.274559,2.015113,5.289673,['nan'],1,False
2,1970-01-01 05:37:30.702100000,https://malijet.com/actualite-sur-afrique/3034...,1#Benin#BN#BN##9.5#2.25#BN#885;1#Benin#BN#BN##...,NaN,"A Committee,112",KILL#2#citizens Benin#1#Togo#TO#TO#8#1.166667#...,no_image,-3.250000,2.750000,6.000000,8.750000,"['NATURAL_DISASTER_DROWNING,1574', 'SLFID_ECON...",47,True
3,1970-01-01 05:37:31.019013000,https://fightnews.com/2025-pfl-africa-semifina...,1#Cameroon#CM#CM##6#12#CM#1901;1#Cameroon#CM#C...,"Africa Smartcage,965;Africa Justin Clarke,2800...","Fighters League,5388",PROTEST#2014##1#Cameroon#CM#CM#6#12#CM#2837;TA...,no_image,-0.473934,3.696682,4.170616,7.867299,"['TAX_FNCACT_REFEREE,2609', 'TAX_FNCACT_REFERE...",64,True
4,1970-01-01 05:37:31.019001500,https://theeagleonline.com.ng/cultural-capital...,"1#Nigerians#NI#NI##10#8#NI#9474;4#Lagos, Lagos...","Bilal Akkouche,9797;Ladi Kwali,10469;Aina Onab...","Coronation Group,97;Coronation Group,1535;Coro...",NaN,https://theeagleonline.com.ng/wp-content/uploa...,5.846299,6.694955,0.848656,7.543612,"['EPU_ECONOMY,3599', 'EPU_ECONOMY,5460', 'EPU_...",61,False

events_clean.csv chargé avec succès.
Premières 5 lignes de events_df:

,Unnamed: 0,SQLDATE,Actor1Name,Actor2Name,Actor1CountryCode,Actor2CountryCode,IsRootEvent,EventCode,EventRootCode,GoldsteinScale,AvgTone,NumMentions,NumSources,NumArticles,ActionGeo_CountryCode,ActionGeo_FullName,SOURCEURL,EventType,article_text
0,0,2025-04-16,benin,rebellion,ben,unknown,1,100,10,-5.0,-12.500000,6,1,6,BN,Benin,https://article.wn.com/view/2026/04/16/Benin_a...,Tensions diplomatiques,Benin activist wanted for 'inciting rebellion'...
1,1,2025-04-16,benin,russia,ben,rus,1,100,10,-5.0,-12.500000,4,1,4,BN,Benin,https://article.wn.com/view/2026/04/16/Benin_a...,Tensions diplomatiques,Benin activist wanted for 'inciting rebellion'...
2,2,2025-03-27,benin,radio station,ben,unknown,0,190,19,-10.0,-0.946372,3,1,3,BN,"Banikoara, Alibori, Benin",https://www.swissinfo.ch/eng/war-peace/women-h...,Violence,Women harvest hope as extremist threat grows i...
3,3,2025-08-24,benin,unknown,ben,unknown,1,17,1,0.0,-2.314815,15,1,10,BN,"Ouidah, Atlantique, Benin",https://english.news.cn/africa/20250824/f847dc...,Diplomatie,Benin marks int'l day for remembrance of slave...
4,4,2025-08-24,beninese,unknown,ben,unknown,1,174,17,-5.0,-2.314815,7,1,7,BN,"Ouidah, Atlantique, Benin",https://english.news.cn/africa/20250824/f847dc...,Tensions socio-politiques,Benin marks int'l day for remembrance of slave...

daily_score.csv chargé avec succès.
Premières 5 lignes de daily_score_df:

      SQLDATE  GoldsteinScale  stability_score      score   status    month
0  2025-01-01        0.135714         0.135714  44.202043  Tension  2025-01
1  2025-01-02       -0.463158        -0.463158  38.648395    Crise  2025-01
2  2025-01-03        0.731034         0.731034  49.722753  Tension  2025-01
3  2025-01-04        2.542857         2.542857  66.524712  Tension  2025-01
4  2025-01-05        2.800000         2.800000  68.909330  Tension  2025-01

Events_clean cc de powerBI.xlsx chargé avec succès.
Premières 5 lignes de events_excel_df:

,SQLDATE,Actor1Name,Actor2Name,Actor1CountryCode,Actor2CountryCode,IsRootEvent,EventCode,GoldsteinScale,AvgTone,NumMentions,NumSources,NumArticles,ActionGeo_CountryCode,ActionGeo_FullName,SOURCEURL,Mois,Type_event,Score risque,Zone securitaire
0,2025-01-01,benin,kamba,ben,unknown,1,42,1.9,3.216374,1,1,1,BN,Benin,https://dailypost.ng/2025/01/01/kebbi-state-se...,2025-01,Coopération,1.9,Sud/Centre
1,2025-01-01,benin,niger,ben,ner,0,40,1.0,-7.901235,3,1,3,BN,Benin,https://saharareporters.com/2025/01/01/benin-s...,2025-01,Coopération,1.0,Sud/Centre
2,2025-01-01,benin,niger,ben,ner,0,57,8.0,-7.901235,2,1,2,BN,Benin,https://saharareporters.com/2025/01/01/benin-s...,2025-01,Tension/Manifestation,8.0,Sud/Centre
3,2025-01-01,benin,nigerien,ben,ner,1,40,1.0,-7.901235,2,1,2,BN,Benin,https://saharareporters.com/2025/01/01/benin-s...,2025-01,Coopération,1.0,Sud/Centre
4,2025-01-01,benin,unknown,ben,unknown,0,30,4.0,-7.901235,4,1,4,BN,Benin,https://saharareporters.com/2025/01/01/benin-s...,2025-01,Coopération,4.0,Sud/Centre

### 1. Nettoyage et préparation de `daily_score_df`

Nous allons d'abord examiner les types de données, convertir la colonne `SQLDATE` en format datetime et vérifier les valeurs manquantes.

In [4]:
print("Informations sur daily_score_df avant nettoyage:")
daily_score_df.info()
print("\nValeurs manquantes dans daily_score_df avant nettoyage:")
print(daily_score_df.isnull().sum())

# Conversion de la colonne 'SQLDATE' en datetime
try:
    daily_score_df['SQLDATE'] = pd.to_datetime(daily_score_df['SQLDATE'])
    print("\nLa colonne 'SQLDATE' a été convertie en type datetime avec succès.")
except Exception as e:
    print(f"Erreur lors de la conversion de 'SQLDATE': {e}")

# Vérification des valeurs manquantes après conversion
print("\nValeurs manquantes dans daily_score_df après conversion:")
print(daily_score_df.isnull().sum())

# Affichage des statistiques descriptives pour les colonnes numériques
print("\nStatistiques descriptives de daily_score_df:")
display(daily_score_df.describe())

Informations sur daily_score_df avant nettoyage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SQLDATE          348 non-null    object
 1   GoldsteinScale   348 non-null    float64
 2   stability_score  348 non-null    float64
 3   score            348 non-null    float64
 4   status           348 non-null    object
 5   month            348 non-null    object
dtypes: float64(3), object(3)
memory usage: 16.4+ KB

Valeurs manquantes dans daily_score_df avant nettoyage:
SQLDATE            0
GoldsteinScale     0
stability_score    0
score              0
status             0
month              0
dtype: int64

La colonne 'SQLDATE' a été convertie en type datetime avec succès.

Valeurs manquantes dans daily_score_df après conversion:
SQLDATE            0
GoldsteinScale     0
stability_score    0
score              0
status             0
month              0
dtype: int64

Statistiques descriptives de daily_score_df:

,SQLDATE,GoldsteinScale,stability_score,score
count,348,348.000000,348.000000,348.000000
mean,2025-07-02 10:33:06.206896640,0.708208,0.708208,49.511068
min,2025-01-01 00:00:00,-4.630769,-4.630769,0.000000
25%,2025-03-28 18:00:00,-0.333654,-0.333654,39.849352
50%,2025-07-10 12:00:00,0.833832,0.833832,50.676042
75%,2025-10-05 06:00:00,1.771753,1.771753,59.373871
max,2025-12-31 00:00:00,6.152632,6.152632,100.000000
std,NaN,1.596397,1.596397,14.804205

### Poursuite du nettoyage de `daily_score_df`

Nous allons maintenant vérifier et supprimer la colonne 'Unnamed: 0' si elle est présente, car elle est souvent redondante.

In [5]:
# Suppression de la colonne 'Unnamed: 0' si elle existe
if 'Unnamed: 0' in daily_score_df.columns:
    daily_score_df = daily_score_df.drop(columns=['Unnamed: 0'])
    print("La colonne 'Unnamed: 0' a été supprimée de daily_score_df.")
else:
    print("La colonne 'Unnamed: 0' n'existe pas dans daily_score_df.")

print("\nInformations sur daily_score_df après nettoyage:")
daily_score_df.info()
print("\nValeurs manquantes dans daily_score_df après suppression de 'Unnamed: 0':")
print(daily_score_df.isnull().sum())

La colonne 'Unnamed: 0' n'existe pas dans daily_score_df.

Informations sur daily_score_df après nettoyage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SQLDATE          348 non-null    datetime64[ns]
 1   GoldsteinScale   348 non-null    float64
 2   stability_score  348 non-null    float64
 3   score            348 non-null    float64
 4   status           348 non-null    object
 5   month            348 non-null    object
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 16.4+ KB

Valeurs manquantes dans daily_score_df après suppression de 'Unnamed: 0':
SQLDATE            0
GoldsteinScale     0
stability_score    0
score              0
status             0
month              0
dtype: int64

### Résumé du nettoyage de `daily_score_df`

Après ces premières étapes, `daily_score_df` est prêt pour l'analyse. La colonne `SQLDATE` est au bon format et la colonne 'Unnamed: 0' a été gérée. Nous n'avons pas de valeurs manquantes importantes dans les colonnes numériques clés.

Nous allons maintenant passer à la préparation de `events_df` et `gkg_df` pour extraire des fonctionnalités potentiellement utiles.

### 2. Nettoyage et préparation de `events_df`

Nous allons appliquer des étapes de nettoyage similaires à `events_df`, en nous concentrant sur la conversion des dates et la gestion des colonnes redondantes.

In [6]:
print("Informations sur events_df avant nettoyage:")
events_df.info()
print("\nValeurs manquantes dans events_df avant nettoyage:")
print(events_df.isnull().sum())

# Conversion de la colonne 'SQLDATE' en datetime
try:
    events_df['SQLDATE'] = pd.to_datetime(events_df['SQLDATE'])
    print("\nLa colonne 'SQLDATE' a été convertie en type datetime avec succès dans events_df.")
except Exception as e:
    print(f"Erreur lors de la conversion de 'SQLDATE' dans events_df: {e}")

# Suppression de la colonne 'Unnamed: 0' si elle existe
if 'Unnamed: 0' in events_df.columns:
    events_df = events_df.drop(columns=['Unnamed: 0'])
    print("La colonne 'Unnamed: 0' a été supprimée de events_df.")
else:
    print("La colonne 'Unnamed: 0' n'existe pas dans events_df.")

print("\nInformations sur events_df après nettoyage:")
events_df.info()
print("\nValeurs manquantes dans events_df après nettoyage:")
print(events_df.isnull().sum())

# Affichage des statistiques descriptives pour les colonnes numériques
print("\nStatistiques descriptives de events_df:")
display(events_df.describe())

Informations sur events_df avant nettoyage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6353 entries, 0 to 6352
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             6353 non-null   int64
 1   SQLDATE                6353 non-null   object
 2   Actor1Name             6353 non-null   object
 3   Actor2Name             6353 non-null   object
 4   Actor1CountryCode      6353 non-null   object
 5   Actor2CountryCode      6353 non-null   object
 6   IsRootEvent            6353 non-null   int64
 7   EventCode              6353 non-null   int64
 8   EventRootCode          6353 non-null   int64
 9   GoldsteinScale         6353 non-null   float64
 10  AvgTone                6353 non-null   float64
 11  NumMentions            6353 non-null   int64
 12  NumSources             6353 non-null   int64
 13  NumArticles            6353 non-null   int64
 14  ActionGeo_CountryCode  6353 non-null   object
 15  ActionGeo_FullName     6353 non-null   object
 16  SOURCEURL              6353 non-null   object
 17  EventType              6353 non-null   object
 18  article_text           5895 non-null   object
dtypes: float64(2), int64(7), object(10)
memory usage: 943.2+ KB

Valeurs manquantes dans events_df avant nettoyage:
Unnamed: 0                 0
SQLDATE                    0
Actor1Name                 0
Actor2Name                 0
Actor1CountryCode          0
Actor2CountryCode          0
IsRootEvent                0
EventCode                  0
EventRootCode              0
GoldsteinScale             0
AvgTone                    0
NumMentions                0
NumSources                 0
NumArticles                0
ActionGeo_CountryCode      0
ActionGeo_FullName         0
SOURCEURL                  0
EventType                  0
article_text             458
dtype: int64

La colonne 'SQLDATE' a été convertie en type datetime avec succès dans events_df.
La colonne 'Unnamed: 0' a été supprimée de events_df.

Informations sur events_df après nettoyage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6353 entries, 0 to 6352
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SQLDATE                6353 non-null   datetime64[ns]
 1   Actor1Name             6353 non-null   object
 2   Actor2Name             6353 non-null   object
 3   Actor1CountryCode      6353 non-null   object
 4   Actor2CountryCode      6353 non-null   object
 5   IsRootEvent            6353 non-null   int64
 6   EventCode              6353 non-null   int64
 7   EventRootCode          6353 non-null   int64
 8   GoldsteinScale         6353 non-null   float64
 9   AvgTone                6353 non-null   float64
 10  NumMentions            6353 non-null   int64
 11  NumSources             6353 non-null   int64
 12  NumArticles            6353 non-null   int64
 13  ActionGeo_CountryCode  6353 non-null   object
 14  ActionGeo_FullName     6353 non-null   object
 15  SOURCEURL              6353 non-null   object
 16  EventType              6353 non-null   object
 17  article_text           5895 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(6), object(9)
memory usage: 893.5+ KB

Valeurs manquantes dans events_df après nettoyage:
SQLDATE                    0
Actor1Name                 0
Actor2Name                 0
Actor1CountryCode          0
Actor2CountryCode          0
IsRootEvent                0
EventCode                  0
EventRootCode              0
GoldsteinScale             0
AvgTone                    0
NumMentions                0
NumSources                 0
NumArticles                0
ActionGeo_CountryCode      0
ActionGeo_FullName         0
SOURCEURL                  0
EventType                  0
article_text             458
dtype: int64

Statistiques descriptives de events_df:

,SQLDATE,IsRootEvent,EventCode,EventRootCode,GoldsteinScale,AvgTone,NumMentions,NumSources,NumArticles
count,6353,6353.000000,6353.000000,6353.000000,6353.000000,6353.000000,6353.000000,6353.000000,6353.000000
mean,2025-07-12 00:44:11.975444480,0.626476,84.050212,6.375256,0.654604,-1.080096,5.119314,1.008185,4.988824
min,2025-01-01 00:00:00,0.000000,10.000000,1.000000,-10.000000,-17.241379,1.000000,1.000000,1.000000
25%,2025-04-02 00:00:00,0.000000,30.000000,2.000000,-2.000000,-4.273504,2.000000,1.000000,2.000000
50%,2025-07-16 00:00:00,1.000000,46.000000,4.000000,1.900000,-0.954654,4.000000,1.000000,4.000000
75%,2025-11-04 00:00:00,1.000000,110.000000,9.000000,3.400000,2.312139,8.000000,1.000000,8.000000
max,2025-12-31 00:00:00,1.000000,1822.000000,19.000000,10.000000,19.480519,48.000000,4.000000,48.000000
std,NaN,0.483778,156.371020,5.325864,4.401887,4.542312,3.997511,0.095205,3.673725

### 3. Nettoyage et préparation de `gkg_df`

Nous allons maintenant nettoyer `gkg_df` en nous concentrant sur la colonne de date et la gestion des colonnes redondantes ou inutiles.

In [7]:
print("Informations sur gkg_df avant nettoyage:")
gkg_df.info()
print("\nValeurs manquantes dans gkg_df avant nettoyage:")
print(gkg_df.isnull().sum())

# Conversion de la colonne 'DATE' en datetime
try:
    # La colonne 'DATE' semble être un timestamp Unix ou une chaîne de caractères complexe. Nous allons tenter de la convertir.
    # Si c'est un timestamp, nous devrons peut-être ajuster l'unité.
    # D'après l'aperçu, elle ressemble à un format datetime standard, mais avec une précision élevée.
    gkg_df['DATE'] = pd.to_datetime(gkg_df['DATE'])
    print("\nLa colonne 'DATE' a été convertie en type datetime avec succès dans gkg_df.")
except Exception as e:
    print(f"Erreur lors de la conversion de 'DATE' dans gkg_df: {e}")

# Suppression de la colonne 'Unnamed: 0' si elle existe (bien que peu probable pour gkg_df initialement)
if 'Unnamed: 0' in gkg_df.columns:
    gkg_df = gkg_df.drop(columns=['Unnamed: 0'])
    print("La colonne 'Unnamed: 0' a été supprimée de gkg_df.")
else:
    print("La colonne 'Unnamed: 0' n'existe pas dans gkg_df.")

# Vérifier si 'Unnamed: 0.1' existe aussi et le supprimer
if 'Unnamed: 0.1' in gkg_df.columns:
    gkg_df = gkg_df.drop(columns=['Unnamed: 0.1'])
    print("La colonne 'Unnamed: 0.1' a été supprimée de gkg_df.")
else:
    print("La colonne 'Unnamed: 0.1' n'existe pas dans gkg_df.")

print("\nInformations sur gkg_df après nettoyage:")
gkg_df.info()
print("\nValeurs manquantes dans gkg_df après nettoyage:")
print(gkg_df.isnull().sum())

# Affichage des statistiques descriptives pour les colonnes numériques
print("\nStatistiques descriptives de gkg_df:")
display(gkg_df.describe())

Informations sur gkg_df avant nettoyage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47775 entries, 0 to 47774
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                47775 non-null  object
 1   DocumentIdentifier  47775 non-null  object
 2   V2Locations         47775 non-null  object
 3   V2Persons           31915 non-null  object
 4   V2Organizations     36929 non-null  object
 5   V2Counts            6747 non-null   object
 6   SharingImage        47775 non-null  object
 7   tone                47775 non-null  float64
 8   positive_score      47775 non-null  float64
 9   negative_score      47775 non-null  float64
 10  polarity            47775 non-null  float64
 11  themes              47775 non-null  object
 12  themes_count        47775 non-null  int64
 13  has_crisis_theme    47775 non-null  bool
dtypes: bool(1), float64(4), int64(1), object(8)
memory usage: 4.8+ MB

Valeurs manquantes dans gkg_df avant nettoyage:
DATE                      0
DocumentIdentifier        0
V2Locations               0
V2Persons             15860
V2Organizations       10846
V2Counts              41028
SharingImage              0
tone                      0
positive_score            0
negative_score            0
polarity                  0
themes                    0
themes_count              0
has_crisis_theme          0
dtype: int64

La colonne 'DATE' a été convertie en type datetime avec succès dans gkg_df.
La colonne 'Unnamed: 0' n'existe pas dans gkg_df.
La colonne 'Unnamed: 0.1' n'existe pas dans gkg_df.

Informations sur gkg_df après nettoyage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47775 entries, 0 to 47774
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                47775 non-null  datetime64[ns]
 1   DocumentIdentifier  47775 non-null  object
 2   V2Locations         47775 non-null  object
 3   V2Persons           31915 non-null  object
 4   V2Organizations     36929 non-null  object
 5   V2Counts            6747 non-null   object
 6   SharingImage        47775 non-null  object
 7   tone                47775 non-null  float64
 8   positive_score      47775 non-null  float64
 9   negative_score      47775 non-null  float64
 10  polarity            47775 non-null  float64
 11  themes              47775 non-null  object
 12  themes_count        47775 non-null  int64
 13  has_crisis_theme    47775 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 4.8+ MB

Valeurs manquantes dans gkg_df après nettoyage:
DATE                      0
DocumentIdentifier        0
V2Locations               0
V2Persons             15860
V2Organizations       10846
V2Counts              41028
SharingImage              0
tone                      0
positive_score            0
negative_score            0
polarity                  0
themes                    0
themes_count              0
has_crisis_theme          0
dtype: int64

Statistiques descriptives de gkg_df:

,DATE,tone,positive_score,negative_score,polarity,themes_count
count,47775,47775.000000,47775.000000,47775.000000,47775.000000,47775.000000
mean,1970-01-01 05:37:30.723513635,-0.536808,3.346398,3.883206,7.229605,61.916630
min,1970-01-01 05:37:30.101000,-22.857143,0.000000,0.000000,0.000000,1.000000
25%,1970-01-01 05:37:30.404122250,-3.178027,1.944895,1.617959,5.353815,19.000000
50%,1970-01-01 05:37:30.730090,-0.369686,3.007519,3.333333,7.003257,46.000000
75%,1970-01-01 05:37:31.029008750,2.240611,4.436860,5.625000,8.910891,81.000000
max,1970-01-01 05:37:31.231234500,22.540820,24.731183,22.857143,26.921545,3927.000000
std,NaN,3.991041,1.981783,2.811864,2.782026,74.812103

### 4. Nettoyage et préparation de `events_excel_df`

Nous allons maintenant nettoyer `events_excel_df` de manière similaire aux précédents dataframes, en nous concentrant sur la colonne de date et la gestion des colonnes redondantes.

In [8]:
print("Informations sur events_excel_df avant nettoyage:")
events_excel_df.info()
print("\nValeurs manquantes dans events_excel_df avant nettoyage:")
print(events_excel_df.isnull().sum())

# Conversion de la colonne 'SQLDATE' en datetime
try:
    events_excel_df['SQLDATE'] = pd.to_datetime(events_excel_df['SQLDATE'])
    print("\nLa colonne 'SQLDATE' a été convertie en type datetime avec succès dans events_excel_df.")
except Exception as e:
    print(f"Erreur lors de la conversion de 'SQLDATE' dans events_excel_df: {e}")

# Suppression de la colonne 'Unnamed: 0' si elle existe
if 'Unnamed: 0' in events_excel_df.columns:
    events_excel_df = events_excel_df.drop(columns=['Unnamed: 0'])
    print("La colonne 'Unnamed: 0' a été supprimée de events_excel_df.")
else:
    print("La colonne 'Unnamed: 0' n'existe pas dans events_excel_df.")

print("\nInformations sur events_excel_df après nettoyage:")
events_excel_df.info()
print("\nValeurs manquantes dans events_excel_df après nettoyage:")
print(events_excel_df.isnull().sum())

# Affichage des statistiques descriptives pour les colonnes numériques
print("\nStatistiques descriptives de events_excel_df:")
display(events_excel_df.describe())

Informations sur events_excel_df avant nettoyage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SQLDATE                1000 non-null   datetime64[ns]
 1   Actor1Name             1000 non-null   object
 2   Actor2Name             1000 non-null   object
 3   Actor1CountryCode      1000 non-null   object
 4   Actor2CountryCode      1000 non-null   object
 5   IsRootEvent            1000 non-null   int64
 6   EventCode              1000 non-null   int64
 7   GoldsteinScale         1000 non-null   float64
 8   AvgTone                1000 non-null   float64
 9   NumMentions            1000 non-null   int64
 10  NumSources             1000 non-null   int64
 11  NumArticles            1000 non-null   int64
 12  ActionGeo_CountryCode  1000 non-null   object
 13  ActionGeo_FullName     1000 non-null   object
 14  SOURCEURL              1000 non-null   object
 15  Mois                   1000 non-null   object
 16  Type_event             1000 non-null   object
 17  Score risque           1000 non-null   float64
 18  Zone securitaire       1000 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(5), object(10)
memory usage: 148.6+ KB

Valeurs manquantes dans events_excel_df avant nettoyage:
SQLDATE                  0
Actor1Name               0
Actor2Name               0
Actor1CountryCode        0
Actor2CountryCode        0
IsRootEvent              0
EventCode                0
GoldsteinScale           0
AvgTone                  0
NumMentions              0
NumSources               0
NumArticles              0
ActionGeo_CountryCode    0
ActionGeo_FullName       0
SOURCEURL                0
Mois                     0
Type_event               0
Score risque             0
Zone securitaire         0
dtype: int64

La colonne 'SQLDATE' a été convertie en type datetime avec succès dans events_excel_df.
La colonne 'Unnamed: 0' n'existe pas dans events_excel_df.

Informations sur events_excel_df après nettoyage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SQLDATE                1000 non-null   datetime64[ns]
 1   Actor1Name             1000 non-null   object
 2   Actor2Name             1000 non-null   object
 3   Actor1CountryCode      1000 non-null   object
 4   Actor2CountryCode      1000 non-null   object
 5   IsRootEvent            1000 non-null   int64
 6   EventCode              1000 non-null   int64
 7   GoldsteinScale         1000 non-null   float64
 8   AvgTone                1000 non-null   float64
 9   NumMentions            1000 non-null   int64
 10  NumSources             1000 non-null   int64
 11  NumArticles            1000 non-null   int64
 12  ActionGeo_CountryCode  1000 non-null   object
 13  ActionGeo_FullName     1000 non-null   object
 14  SOURCEURL              1000 non-null   object
 15  Mois                   1000 non-null   object
 16  Type_event             1000 non-null   object
 17  Score risque           1000 non-null   float64
 18  Zone securitaire       1000 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(5), object(10)
memory usage: 148.6+ KB

Valeurs manquantes dans events_excel_df après nettoyage:
SQLDATE                  0
Actor1Name               0
Actor2Name               0
Actor1CountryCode        0
Actor2CountryCode        0
IsRootEvent              0
EventCode                0
GoldsteinScale           0
AvgTone                  0
NumMentions              0
NumSources               0
NumArticles              0
ActionGeo_CountryCode    0
ActionGeo_FullName       0
SOURCEURL                0
Mois                     0
Type_event               0
Score risque             0
Zone securitaire         0
dtype: int64

Statistiques descriptives de events_excel_df:

,SQLDATE,IsRootEvent,EventCode,GoldsteinScale,AvgTone,NumMentions,NumSources,NumArticles,Score risque
count,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,2025-01-25 09:00:00,0.657000,79.112000,0.321700,-1.351559,5.703000,1.013000,5.42100,3.422900
min,2025-01-01 00:00:00,0.000000,10.000000,-10.000000,-14.857143,1.000000,1.000000,1.00000,0.000000
25%,2025-01-11 00:00:00,0.000000,25.750000,-2.000000,-4.811378,2.000000,1.000000,2.00000,1.900000
50%,2025-01-21 00:00:00,1.000000,43.000000,1.000000,-1.098901,4.000000,1.000000,4.00000,2.800000
75%,2025-02-10 06:00:00,1.000000,110.000000,3.000000,2.036426,10.000000,1.000000,10.00000,5.000000
max,2025-02-26 00:00:00,1.000000,1821.000000,10.000000,15.044248,40.000000,2.000000,30.00000,10.000000
std,NaN,0.474949,141.039766,4.404234,4.509016,4.511002,0.113331,3.86247,2.787992

### 5. Intégration des DataFrames et Ingénierie de Caractéristiques

Nous allons maintenant préparer les dataframes `events_df`, `gkg_df` et `events_excel_df` pour les fusionner avec `daily_score_df`. L'objectif est d'agréger les informations par date afin d'enrichir notre base de données principale (`daily_score_df`) avec des caractéristiques pertinentes pour la prédiction.

#### 5.1 Préparation des colonnes de date

Nous nous assurons que toutes les colonnes de date sont au format `datetime` et qu'elles ne contiennent que la date (sans l'heure) pour une agrégation journalière cohérente.

In [9]:
# S'assurer que les colonnes de date sont au format datetime et tronquées à la date seule
daily_score_df['SQLDATE'] = daily_score_df['SQLDATE'].dt.normalize()
events_df['SQLDATE'] = events_df['SQLDATE'].dt.normalize()
gkg_df['DATE'] = gkg_df['DATE'].dt.normalize()
events_excel_df['SQLDATE'] = events_excel_df['SQLDATE'].dt.normalize()

# Renommer la colonne 'DATE' de gkg_df en 'SQLDATE' pour une cohérence lors de la fusion
gkg_df.rename(columns={'DATE': 'SQLDATE'}, inplace=True)

print("Colonnes de date normalisées et renommées avec succès.")

# Afficher les informations pour vérifier les types de données et les premières lignes
print("\nInformations sur daily_score_df:")
daily_score_df.info()
print("\nInformations sur events_df:")
events_df.info()
print("\nInformations sur gkg_df:")
gkg_df.info()
print("\nInformations sur events_excel_df:")
events_excel_df.info()

Colonnes de date normalisées et renommées avec succès.

Informations sur daily_score_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SQLDATE          348 non-null    datetime64[ns]
 1   GoldsteinScale   348 non-null    float64
 2   stability_score  348 non-null    float64
 3   score            348 non-null    float64
 4   status           348 non-null    object
 5   month            348 non-null    object
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 16.4+ KB

Informations sur events_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6353 entries, 0 to 6352
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SQLDATE                6353 non-null   datetime64[ns]
 1   Actor1Name             6353 non-null   object
 2   Actor2Name             6353 non-null   object
 3   Actor1CountryCode      6353 non-null   object
 4   Actor2CountryCode      6353 non-null   object
 5   IsRootEvent            6353 non-null   int64
 6   EventCode              6353 non-null   int64
 7   EventRootCode          6353 non-null   int64
 8   GoldsteinScale         6353 non-null   float64
 9   AvgTone                6353 non-null   float64
 10  NumMentions            6353 non-null   int64
 11  NumSources             6353 non-null   int64
 12  NumArticles            6353 non-null   int64
 13  ActionGeo_CountryCode  6353 non-null   object
 14  ActionGeo_FullName     6353 non-null   object
 15  SOURCEURL              6353 non-null   object
 16  EventType              6353 non-null   object
 17  article_text           5895 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(6), object(9)
memory usage: 893.5+ KB

Informations sur gkg_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47775 entries, 0 to 47774
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SQLDATE             47775 non-null  datetime64[ns]
 1   DocumentIdentifier  47775 non-null  object
 2   V2Locations         47775 non-null  object
 3   V2Persons           31915 non-null  object
 4   V2Organizations     36929 non-null  object
 5   V2Counts            6747 non-null   object
 6   SharingImage        47775 non-null  object
 7   tone                47775 non-null  float64
 8   positive_score      47775 non-null  float64
 9   negative_score      47775 non-null  float64
 10  polarity            47775 non-null  float64
 11  themes              47775 non-null  object
 12  themes_count        47775 non-null  int64
 13  has_crisis_theme    47775 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 4.8+ MB

Informations sur events_excel_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SQLDATE                1000 non-null   datetime64[ns]
 1   Actor1Name             1000 non-null   object
 2   Actor2Name             1000 non-null   object
 3   Actor1CountryCode      1000 non-null   object
 4   Actor2CountryCode      1000 non-null   object
 5   IsRootEvent            1000 non-null   int64
 6   EventCode              1000 non-null   int64
 7   GoldsteinScale         1000 non-null   float64
 8   AvgTone                1000 non-null   float64
 9   NumMentions            1000 non-null   int64
 10  NumSources             1000 non-null   int64
 11  NumArticles            1000 non-null   int64
 12  ActionGeo_CountryCode  1000 non-null   object
 13  ActionGeo_FullName     1000 non-null   object
 14  SOURCEURL              1000 non-null   object
 15  Mois                   1000 non-null   object
 16  Type_event             1000 non-null   object
 17  Score risque           1000 non-null   float64
 18  Zone securitaire       1000 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(5), object(10)
memory usage: 148.6+ KB

#### 5.2 Agrégation de `events_df` par jour

Nous allons agréger les caractéristiques clés de `events_df` par `SQLDATE` pour obtenir des statistiques journalières.

In [10]:
events_daily_agg = events_df.groupby('SQLDATE').agg(
    events_goldstein_mean=('GoldsteinScale', 'mean'),
    events_goldstein_sum=('GoldsteinScale', 'sum'),
    events_avgtone_mean=('AvgTone', 'mean'),
    events_avgtone_sum=('AvgTone', 'sum'),
    events_nummentions_sum=('NumMentions', 'sum'),
    events_numsources_sum=('NumSources', 'sum'),
    events_numarticles_sum=('NumArticles', 'sum'),
    events_isrootevent_sum=('IsRootEvent', 'sum'),
    events_count=('SQLDATE', 'count') # Nombre total d'événements par jour
).reset_index()

print("Agrégation journalière de events_df effectuée avec succès.")
print("Premières 5 lignes de events_daily_agg:")
display(events_daily_agg.head())

Agrégation journalière de events_df effectuée avec succès.
Premières 5 lignes de events_daily_agg:

,SQLDATE,events_goldstein_mean,events_goldstein_sum,events_avgtone_mean,events_avgtone_sum,events_nummentions_sum,events_numsources_sum,events_numarticles_sum,events_isrootevent_sum,events_count
0,2025-01-01,0.135714,3.8,-4.040218,-113.126108,107,28,102,18,28
1,2025-01-02,-0.463158,-8.8,-4.811236,-91.413477,98,19,96,14,19
2,2025-01-03,0.731034,21.2,-1.673170,-48.521932,147,30,140,15,29
3,2025-01-04,2.542857,17.8,2.007905,14.055338,33,7,33,6,7
4,2025-01-05,2.800000,33.6,3.480787,41.769441,46,12,44,8,12

#### 5.3 Agrégation de `gkg_df` par jour

Nous allons agréger les caractéristiques clés de `gkg_df` par `SQLDATE` pour obtenir des statistiques journalières.

In [11]:
gkg_daily_agg = gkg_df.groupby('SQLDATE').agg(
    gkg_tone_mean=('tone', 'mean'),
    gkg_tone_sum=('tone', 'sum'),
    gkg_pos_score_mean=('positive_score', 'mean'),
    gkg_neg_score_mean=('negative_score', 'mean'),
    gkg_polarity_mean=('polarity', 'mean'),
    gkg_themes_count_sum=('themes_count', 'sum'),
    gkg_has_crisis_theme_sum=('has_crisis_theme', 'sum'),
    gkg_count=('SQLDATE', 'count') # Nombre total d'entrées GKG par jour
).reset_index()

print("Agrégation journalière de gkg_df effectuée avec succès.")
print("Premières 5 lignes de gkg_daily_agg:")
display(gkg_daily_agg.head())

Agrégation journalière de gkg_df effectuée avec succès.
Premières 5 lignes de gkg_daily_agg:

,SQLDATE,gkg_tone_mean,gkg_tone_sum,gkg_pos_score_mean,gkg_neg_score_mean,gkg_polarity_mean,gkg_themes_count_sum,gkg_has_crisis_theme_sum,gkg_count
0,1970-01-01,-0.536808,-25646.004387,3.346398,3.883206,7.229605,2958067,27936,47775

#### 5.4 Agrégation de `events_excel_df` par jour

Nous allons agréger les caractéristiques clés de `events_excel_df` par `SQLDATE` pour obtenir des statistiques journalières.

In [12]:
events_excel_daily_agg = events_excel_df.groupby('SQLDATE').agg(
    excel_goldstein_mean=('GoldsteinScale', 'mean'),
    excel_goldstein_sum=('GoldsteinScale', 'sum'),
    excel_avgtone_mean=('AvgTone', 'mean'),
    excel_avgtone_sum=('AvgTone', 'sum'),
    excel_nummentions_sum=('NumMentions', 'sum'),
    excel_numsources_sum=('NumSources', 'sum'),
    excel_numarticles_sum=('NumArticles', 'sum'),
    excel_score_risque_mean=('Score risque', 'mean'),
    excel_score_risque_sum=('Score risque', 'sum'),
    excel_count=('SQLDATE', 'count') # Nombre total d'événements Excel par jour
).reset_index()

print("Agrégation journalière de events_excel_df effectuée avec succès.")
print("Premières 5 lignes de events_excel_daily_agg:")
display(events_excel_daily_agg.head())

Agrégation journalière de events_excel_df effectuée avec succès.
Premières 5 lignes de events_excel_daily_agg:

,SQLDATE,excel_goldstein_mean,excel_goldstein_sum,excel_avgtone_mean,excel_avgtone_sum,excel_nummentions_sum,excel_numsources_sum,excel_numarticles_sum,excel_score_risque_mean,excel_score_risque_sum,excel_count
0,2025-01-01,0.135714,3.8,-4.040218,-113.126108,107,28,102,2.707143,75.8,28
1,2025-01-02,-0.463158,-8.8,-4.811236,-91.413477,98,19,96,2.694737,51.2,19
2,2025-01-03,0.731034,21.2,-1.673170,-48.521932,147,30,140,4.110345,119.2,29
3,2025-01-04,2.542857,17.8,2.007905,14.055338,33,7,33,5.400000,37.8,7
4,2025-01-05,2.800000,33.6,3.480787,41.769441,46,12,44,2.800000,33.6,12

#### 5.5 Fusion des DataFrames agrégés avec `daily_score_df`

Nous allons maintenant fusionner tous les dataframes agrégés avec `daily_score_df` en utilisant la colonne `SQLDATE` comme clé. Nous utiliserons un `left join` pour conserver toutes les dates de `daily_score_df` et gérerons les valeurs manquantes résultantes de la fusion.

In [13]:
merged_df = daily_score_df.copy()

# Fusionner avec events_daily_agg
merged_df = pd.merge(merged_df, events_daily_agg, on='SQLDATE', how='left')

# Fusionner avec gkg_daily_agg
merged_df = pd.merge(merged_df, gkg_daily_agg, on='SQLDATE', how='left')

# Fusionner avec events_excel_daily_agg
merged_df = pd.merge(merged_df, events_excel_daily_agg, on='SQLDATE', how='left')

# Remplacer les NaN introduits par les fusions (lorsqu'il n'y avait pas d'événements pour une date donnée) par 0
# Pour les colonnes d'agrégation numérique, c'est généralement un choix sûr
merged_df.fillna(0, inplace=True)

print("Tous les dataframes ont été fusionnés avec succès.")
print("Informations sur le dataframe fusionné (merged_df):")
merged_df.info()
print("\nPremières 5 lignes du dataframe fusionné:")
display(merged_df.head())

Tous les dataframes ont été fusionnés avec succès.
Informations sur le dataframe fusionné (merged_df):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SQLDATE                   348 non-null    datetime64[ns]
 1   GoldsteinScale            348 non-null    float64
 2   stability_score           348 non-null    float64
 3   score                     348 non-null    float64
 4   status                    348 non-null    object
 5   month                     348 non-null    object
 6   events_goldstein_mean     348 non-null    float64
 7   events_goldstein_sum      348 non-null    float64
 8   events_avgtone_mean       348 non-null    float64
 9   events_avgtone_sum        348 non-null    float64
 10  events_nummentions_sum    348 non-null    int64
 11  events_numsources_sum     348 non-null    int64
 12  events_numarticles_sum    348 non-null    int64
 13  events_isrootevent_sum    348 non-null    int64
 14  events_count              348 non-null    int64
 15  gkg_tone_mean             348 non-null    float64
 16  gkg_tone_sum              348 non-null    float64
 17  gkg_pos_score_mean        348 non-null    float64
 18  gkg_neg_score_mean        348 non-null    float64
 19  gkg_polarity_mean         348 non-null    float64
 20  gkg_themes_count_sum      348 non-null    float64
 21  gkg_has_crisis_theme_sum  348 non-null    float64
 22  gkg_count                 348 non-null    float64
 23  excel_goldstein_mean      348 non-null    float64
 24  excel_goldstein_sum       348 non-null    float64
 25  excel_avgtone_mean        348 non-null    float64
 26  excel_avgtone_sum         348 non-null    float64
 27  excel_nummentions_sum     348 non-null    float64
 28  excel_numsources_sum      348 non-null    float64
 29  excel_numarticles_sum     348 non-null    float64
 30  excel_score_risque_mean   348 non-null    float64
 31  excel_score_risque_sum    348 non-null    float64
 32  excel_count               348 non-null    float64
dtypes: datetime64[ns](1), float64(25), int64(5), object(2)
memory usage: 89.8+ KB

Premières 5 lignes du dataframe fusionné:

,SQLDATE,GoldsteinScale,stability_score,score,status,month,events_goldstein_mean,events_goldstein_sum,events_avgtone_mean,events_avgtone_sum,...,excel_goldstein_mean,excel_goldstein_sum,excel_avgtone_mean,excel_avgtone_sum,excel_nummentions_sum,excel_numsources_sum,excel_numarticles_sum,excel_score_risque_mean,excel_score_risque_sum,excel_count
0,2025-01-01,0.135714,0.135714,44.202043,Tension,2025-01,0.135714,3.8,-4.040218,-113.126108,...,0.135714,3.8,-4.040218,-113.126108,107.0,28.0,102.0,2.707143,75.8,28.0
1,2025-01-02,-0.463158,-0.463158,38.648395,Crise,2025-01,-0.463158,-8.8,-4.811236,-91.413477,...,-0.463158,-8.8,-4.811236,-91.413477,98.0,19.0,96.0,2.694737,51.2,19.0
2,2025-01-03,0.731034,0.731034,49.722753,Tension,2025-01,0.731034,21.2,-1.673170,-48.521932,...,0.731034,21.2,-1.673170,-48.521932,147.0,30.0,140.0,4.110345,119.2,29.0
3,2025-01-04,2.542857,2.542857,66.524712,Tension,2025-01,2.542857,17.8,2.007905,14.055338,...,2.542857,17.8,2.007905,14.055338,33.0,7.0,33.0,5.400000,37.8,7.0
4,2025-01-05,2.800000,2.800000,68.909330,Tension,2025-01,2.800000,33.6,3.480787,41.769441,...,2.800000,33.6,3.480787,41.769441,46.0,12.0,44.0,2.800000,33.6,12.0

### 6. Ingénierie de Caractéristiques Supplémentaires (Time-Based Features)

Pour la modélisation de séries temporelles, il est souvent bénéfique d'ajouter des caractéristiques basées sur le temps. Nous allons extraire des informations de la colonne `SQLDATE`.

In [14]:
merged_df['year'] = merged_df['SQLDATE'].dt.year
merged_df['month'] = merged_df['SQLDATE'].dt.month
merged_df['day'] = merged_df['SQLDATE'].dt.day
merged_df['day_of_week'] = merged_df['SQLDATE'].dt.dayofweek # Lundi=0, Dimanche=6
merged_df['day_of_year'] = merged_df['SQLDATE'].dt.dayofyear
merged_df['week_of_year'] = merged_df['SQLDATE'].dt.isocalendar().week.astype(int)
merged_df['quarter'] = merged_df['SQLDATE'].dt.quarter
merged_df['is_weekend'] = merged_df['day_of_week'].isin([5, 6]).astype(int) # 1 si week-end, 0 sinon

print("Caractéristiques temporelles ajoutées avec succès.")
print("Premières 5 lignes du dataframe fusionné avec les nouvelles caractéristiques:")
display(merged_df.head())

Caractéristiques temporelles ajoutées avec succès.
Premières 5 lignes du dataframe fusionné avec les nouvelles caractéristiques:

,SQLDATE,GoldsteinScale,stability_score,score,status,month,events_goldstein_mean,events_goldstein_sum,events_avgtone_mean,events_avgtone_sum,...,excel_score_risque_mean,excel_score_risque_sum,excel_count,year,day,day_of_week,day_of_year,week_of_year,quarter,is_weekend
0,2025-01-01,0.135714,0.135714,44.202043,Tension,1,0.135714,3.8,-4.040218,-113.126108,...,2.707143,75.8,28.0,2025,1,2,1,1,1,0
1,2025-01-02,-0.463158,-0.463158,38.648395,Crise,1,-0.463158,-8.8,-4.811236,-91.413477,...,2.694737,51.2,19.0,2025,2,3,2,1,1,0
2,2025-01-03,0.731034,0.731034,49.722753,Tension,1,0.731034,21.2,-1.673170,-48.521932,...,4.110345,119.2,29.0,2025,3,4,3,1,1,0
3,2025-01-04,2.542857,2.542857,66.524712,Tension,1,2.542857,17.8,2.007905,14.055338,...,5.400000,37.8,7.0,2025,4,5,4,1,1,1
4,2025-01-05,2.800000,2.800000,68.909330,Tension,1,2.800000,33.6,3.480787,41.769441,...,2.800000,33.6,12.0,2025,5,6,5,1,1,1

### 7. Préparation des Données pour la Modélisation

Nous allons maintenant définir nos variables cibles (`y`) et nos caractéristiques (`X`), puis diviser le jeu de données en ensembles d'entraînement et de test de manière chronologique.

In [15]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report

# Convertir 'status' en une variable cible numérique pour la détection de crise
# Par exemple: 0 pour 'Tension', 1 pour 'Crise'
merged_df['status_encoded'] = merged_df['status'].map({'Tension': 0, 'Crise': 1})
print("Encodage de la colonne 'status' effectué.")
print(merged_df['status_encoded'].value_counts())

# Supprimer les lignes où 'status_encoded' est NaN pour la classification
# Cette étape est cruciale car les modèles de scikit-learn ne gèrent pas les NaN dans la variable cible.
merged_df.dropna(subset=['status_encoded'], inplace=True)
print(f"\nNombre de lignes après suppression des NaN dans 'status_encoded': {len(merged_df)}")

# Définir la variable cible pour la prédiction temporelle (score)
y_score = merged_df['score']

# Définir la variable cible pour la détection de crise (status encodé)
y_status = merged_df['status_encoded']

# Définir les caractéristiques (X) en excluant les cibles et les colonnes non pertinentes
# 'SQLDATE' est exclue car nous avons extrait des caractéristiques temporelles
# 'status' est exclue car nous utilisons 'status_encoded' comme cible de classification
# 'score' et 'stability_score' sont exclues car ce sont nos cibles de régression/prédiction
features_to_drop = ['SQLDATE', 'status', 'score', 'stability_score', 'status_encoded']
X = merged_df.drop(columns=[col for col in features_to_drop if col in merged_df.columns])

# Gérer les colonnes non numériques qui pourraient être encore présentes dans X
# Pour cet exemple, nous allons simplement les supprimer. Dans un cas réel, on pourrait les encoder.
for col in X.columns:
    if X[col].dtype == 'object':
        X = X.drop(columns=[col])

print("\nVariables cibles et caractéristiques définies.")
print(f"Forme de X: {X.shape}")
print(f"Forme de y_score: {y_score.shape}")
print(f"Forme de y_status: {y_status.shape}")

# Split chronologique des données
# Utilisons 80% des données pour l'entraînement et 20% pour le test
train_size = int(len(merged_df) * 0.8)
X_train, X_test = X.iloc[:train_size], X.iloc[train_size:]
y_score_train, y_score_test = y_score.iloc[:train_size], y_score.iloc[train_size:]
y_status_train, y_status_test = y_status.iloc[:train_size], y_status.iloc[train_size:]

print(f"\nDonnées divisées en ensembles d'entraînement et de test (split temporel):")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_score_train shape: {y_score_train.shape}")
print(f"y_score_test shape: {y_score_test.shape}")
print(f"y_status_train shape: {y_status_train.shape}")
print(f"y_status_test shape: {y_status_test.shape}")

Encodage de la colonne 'status' effectué.
status_encoded
0.0    238
1.0     88
Name: count, dtype: int64

Nombre de lignes après suppression des NaN dans 'status_encoded': 326

Variables cibles et caractéristiques définies.
Forme de X: (326, 36)
Forme de y_score: (326,)
Forme de y_status: (326,)

Données divisées en ensembles d'entraînement et de test (split temporel):
X_train shape: (260, 36)
X_test shape: (66, 36)
y_score_train shape: (260,)
y_score_test shape: (66,)
y_status_train shape: (260,)
y_status_test shape: (66,)

### 8. Construction et Évaluation des Modèles

Nous allons construire un modèle de régression pour prédire le `score` et un modèle de classification pour détecter le `status` de crise.

#### 8.1 Modèle de Prédiction du Score (Régression)

In [16]:
# Initialiser et entraîner un modèle de régression (RandomForestRegressor)
model_score = RandomForestRegressor(n_estimators=100, random_state=42)
model_score.fit(X_train, y_score_train)

# Faire des prédictions sur l'ensemble de test
y_score_pred = model_score.predict(X_test)

# Évaluer le modèle
mse = mean_squared_error(y_score_test, y_score_pred)
rmse = np.sqrt(mse)

print(f"\nPerformance du modèle de prédiction du score:")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")

# Afficher les premières prédictions vs. valeurs réelles
print("\nComparaison des valeurs réelles et prédites (score):")
comparison_score = pd.DataFrame({'Réel': y_score_test, 'Prédit': y_score_pred})
display(comparison_score.head())

Performance du modèle de prédiction du score:
Mean Squared Error (MSE): 0.26
Root Mean Squared Error (RMSE): 0.51

Comparaison des valeurs réelles et prédites (score):

          Réel     Prédit
275  51.907891  52.039549
276  44.798198  44.920960
277  52.402478  52.347632
278   6.405857   8.595364
279  62.830027  62.666656

#### 8.2 Modèle de Détection de Crise (Classification)

In [17]:
# Initialiser et entraîner un modèle de classification (RandomForestClassifier)
model_status = RandomForestClassifier(n_estimators=100, random_state=42)
model_status.fit(X_train, y_status_train)

# Faire des prédictions sur l'ensemble de test
y_status_pred = model_status.predict(X_test)

# Évaluer le modèle
accuracy = accuracy_score(y_status_test, y_status_pred)
classification_rep = classification_report(y_status_test, y_status_pred)

print(f"\nPerformance du modèle de détection de crise:")
print(f"Accuracy: {accuracy:.2f}")
print("\nRapport de classification:\n")
print(classification_rep)

# Afficher les premières prédictions vs. valeurs réelles
print("\nComparaison des valeurs réelles et prédites (statut):")
comparison_status = pd.DataFrame({'Réel': y_status_test, 'Prédit': y_status_pred})
display(comparison_status.head())

Performance du modèle de détection de crise:
Accuracy: 0.98

Rapport de classification:

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99        46
         1.0       1.00      0.95      0.97        20

    accuracy                           0.98        66
   macro avg       0.99      0.97      0.98        66
weighted avg       0.99      0.98      0.98        66


Comparaison des valeurs réelles et prédites (statut):

     Réel  Prédit
275   0.0     0.0
276   0.0     0.0
277   0.0     0.0
278   1.0     1.0
279   0.0     0.0

### 7. Préparation des Données pour la Modélisation

Nous allons maintenant définir nos variables cibles (`y`) et nos caractéristiques (`X`), puis diviser le jeu de données en ensembles d'entraînement et de test de manière chronologique.

In [18]:
# Convertir 'status' en une variable cible numérique pour la détection de crise
# Par exemple: 0 pour 'Tension', 1 pour 'Crise'
merged_df['status_encoded'] = merged_df['status'].map({'Tension': 0, 'Crise': 1})
print("Encodage de la colonne 'status' effectué.")
print(merged_df['status_encoded'].value_counts())

# Définir la variable cible pour la prédiction temporelle (score)
y_score = merged_df['score']

# Définir la variable cible pour la détection de crise (status encodé)
y_status = merged_df['status_encoded']

# Définir les caractéristiques (X) en excluant les cibles et les colonnes non pertinentes
# 'SQLDATE' est exclue car nous avons extrait des caractéristiques temporelles
# 'status' est exclue car nous utilisons 'status_encoded' comme cible de classification
# 'score' et 'stability_score' sont exclues car ce sont nos cibles de régression/prédiction
features_to_drop = ['SQLDATE', 'status', 'score', 'stability_score', 'status_encoded']
X = merged_df.drop(columns=[col for col in features_to_drop if col in merged_df.columns])

print("\nVariables cibles et caractéristiques définies.")
print(f"Forme de X: {X.shape}")
print(f"Forme de y_score: {y_score.shape}")
print(f"Forme de y_status: {y_status.shape}")

# Split chronologique des données
# Utilisons 80% des données pour l'entraînement et 20% pour le test
train_size = int(len(merged_df) * 0.8)
X_train, X_test = X.iloc[:train_size], X.iloc[train_size:]
y_score_train, y_score_test = y_score.iloc[:train_size], y_score.iloc[train_size:]
y_status_train, y_status_test = y_status.iloc[:train_size], y_status.iloc[train_size:]

print(f"\nDonnées divisées en ensembles d'entraînement et de test (split temporel):")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_score_train shape: {y_score_train.shape}")
print(f"y_score_test shape: {y_score_test.shape}")
print(f"y_status_train shape: {y_status_train.shape}")
print(f"y_status_test shape: {y_status_test.shape}")

Encodage de la colonne 'status' effectué.
status_encoded
0    238
1     88
Name: count, dtype: int64

Variables cibles et caractéristiques définies.
Forme de X: (326, 36)
Forme de y_score: (326,)
Forme de y_status: (326,)

Données divisées en ensembles d'entraînement et de test (split temporel):
X_train shape: (260, 36)
X_test shape: (66, 36)
y_score_train shape: (260,)
y_score_test shape: (66,)
y_status_train shape: (260,)
y_status_test shape: (66,)